### ISSUE TITLE
Mugshot stuck in "grimace" state

### ISSUE THREAD

**Issue by caligari87** [caligari87/tranquility#25]
No idea what's causing this.

**Comment by MatthewTheGlutton** [comment]
It seems like it needs a WeaponReady call that allows firing.

I can get rid of the perpetual grimace if I replace:
```
	Fire:
		//Placeholder
	Ready:
		TNT1 A 0 TQ_InitializeOverlays();
		//Intentional fallthrough to Primary context

	//Primary Weapon Action States
	Primary.Ready:
		TNT1 A 1 TQ_PrimaryInput;
		Loop;
```
with:
```
	Fire:
	Altfire:
		TNT1 A 0{
			TQ_PrimaryInput();
			A_WeaponReady(WRF_NOFIRE);
			A_ClearRefire();
		}goto ready;
		//Placeholder
	Ready:
		TNT1 A 0 TQ_InitializeOverlays();
		//Intentional fallthrough to Primary context

		//Primary Weapon Action States
	Primary.Ready:
		TNT1 A 1 TQ_PrimaryInput();
		TNT1 A 0 A_WeaponReady();
		Loop;
```

**Comment by caligari87** [comment]
Seems the grimace face is based on how many tics since `A_WeaponReady` has been called, and I can't use `WRF_NOFIRE` to disable the stock states.

**Comment by caligari87** [comment]
After some fiddling, I've decided to ignore this for the time being. This mod isn't really intended to be used with the stock statusbar anyway, and I'll probably remove it in favor of a custom HUD at some point.

**Comment by MatthewTheGlutton** [comment]
So what about my proposed solution of allowing fire, but having the fire states repeat the stuff as the ready state?

**Comment by caligari87** [comment]
I actually think I may have sort-of solved this with the re-write I'm working on. Since everything is handled by GetPlayerInput checks, an actual "Fire" eventcaught by A_WeaponReady just dumps back to Ready. Altfire can get caught as well but goes to the right place anyway.
